### ISSUE TITLE
AddOn 'NamePlatesThreat' tried to call the protected function 'SetTargetClampingInsets()'

### ISSUE THREAD

**Issue by dieterdanger** [int3ro/Nameplates_Threat#24]
Dragonflight Prepatch

2x [ADDON_ACTION_BLOCKED] AddOn 'NamePlatesThreat' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:395: in function `SetupClassNameplateBars'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:143: in function `OnNamePlateAdded'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:69>

**Comment by mikfhan** [comment]
Ah, yeah this one is tricky, see the [issue](https://www.curseforge.com/wow/addons/blizzard-nameplates-threat/issues/9) reported on CurseForge also pointing to an even older [issue](https://www.curseforge.com/wow/addons/blizzard-nameplates-threat/issues/7) of same "vague UI taint".

Looks like I was right the UI taint is not 100% fixed yet, you could either /console scriptErrors 0 to hide the popups and make do for now, or find and disable the BugGrabber addon reporting the taint (it might be a subfolder to one of your other addons).

It might be possible to live with this taint as long as it won't prevent combat actions, but I really would like to fix it permanently somehow, just have to read up on this "vague UI taint" from SetTargetClampingInsets that apparently has troubled addon makers for many years. Strange stuff - the work continues! :D If others have ideas on this do tell.
