### ISSUE TITLE
Attempt to access forbidden object from code tainted by an AddOn [string "=[C]"]: in function `SetOwner'

### ISSUE THREAD

**Issue by dieterdanger** [int3ro/Nameplates_Threat#25]
1x ...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:854: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `SetOwner'
[string "@Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua"]:854: in function <...e/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:853>

Locals:
(*temporary) = NamePlateTooltip {
 waitingForData = false
 layoutType = "TooltipDefaultLayout"
 textLeft1Font = "GameTooltipHeaderText"
 BottomOverlay = Texture {
 }
 textRight1Font = "GameTooltipHeaderText"
 NineSlice = Frame {
 }
 TextRight1 = NamePlateTooltipTextRight1 {
 }
 TextRight2 = NamePlateTooltipTextRight2 {
 }
 TextLeft2 = NamePlateTooltipTextLeft2 {
 }
 TopOverlay = Texture {
 }
 comparing = false
 0 = <userdata>
 needsReset = true
 textLeft2Font = "GameTooltipText"
 textRight2Font = "GameTooltipText"
 TextLeft1 = NamePlateTooltipTextLeft1 {
 }
 updateTooltipTimer = 0.168000
}
(*temporary) = Frame {
 0 = <userdata>
 OnLeave = <function> defined @Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:866
 auraInstanceID = 76148
 layoutIndex = 1
 Border = Texture {
 }
 isBuff = true
 Cooldown = Cooldown {
 }
 OnEnter = <function> defined @Interface/AddOns/Blizzard_NamePlates/Blizzard_NamePlates.lua:853
 CountFrame = Frame {
 }
 Icon = Texture {
 }
 spellID = 202090
}
(*temporary) = "ANCHOR_LEFT"

**Comment by mikfhan** [comment]
This might be a later symptom of the SetTargetClampingInsets "vague UI taint" [issue](https://github.com/int3ro/Nameplates_Threat/issues/24) later infecting default Blizzard UI panels (this is exactly what "tainting" does if untreated). Once that taint issue is solved this one should go away for good I hope, and hope it's not preventing important combat actions in the meantime :)
