### ISSUE TITLE
Colors don't always reset out of dungeon/combat

### ISSUE THREAD

**Issue by mikfhan** [int3ro/Nameplates_Threat#31]
From rakkarage: Thanks a lot. Indispensable addon. After doing a dungeon some nameplate colors are messed up in world?

I have it set to only work in instance but when i come out sometimes some mobs have purple or different colors, at first i thought it meant something like those mobs have buffs but then i realized it is just a bug:

https://i.postimg.cc/W3qffzkV/Wo-WScrn-Shot-020623-142231.jpg
reload fixes it
https://i.postimg.cc/5yckcJBC/Wo-WScrn-Shot-020623-142242.jpg

**Comment by mikfhan** [comment]
If anyone is interested testing the bugfix, try replacing content of your nameplatesthreat.lua with the below:

https://raw.githubusercontent.com/int3ro/Nameplates_Threat/da49a3b10d0fd15448f02f3e608ef2be8a9922e3/NamePlatesThreat.lua

It should be better at resetting nameplate frames when you're not in a dungeon/combat.

**Comment by Stclv** [comment]
looks great

**Comment by mikfhan** [comment]
If disabled, the out-of-combat colors will still be used while you are in combat, for those monsters that are not part of it. So you can see faraway monsters' reputation hostile vs neutral. Is that what's happening maybe?

**Comment by Stclv** [comment]
works as expected. good explanaition!
