### ISSUE TITLE
Colors change on random targeting

### ISSUE THREAD

**Issue by mikfhan** [int3ro/Nameplates_Threat#34]
Some mobs/bosses randomly target someone regardless of threat percentage, confusing the nameplate coloring. Maybe ignore those situations for mob/boss coloring and only measure actual threat percentage. Only using actual target for coloring PvP enemy players.

Maybe try copying contents of link below, replacing all inside your addon folder NamePlatesThreat.lua file, and let me know here if it has issues still to sort out:

https://raw.githubusercontent.com/int3ro/Nameplates_Threat/mikfhan/NamePlatesThreat.lua

**Comment by rakkarage** [comment]
This seems to be new with 10.0.7... Mobs are constantly changing colors in dungeons and raids whenever they cast a spell or target anyone? maybe something changed in the way they calculate threat or a bug cuz colors are flickering even when tank has aggro? idk i am testing this file and seems to fix it so far thanks

**Comment by mikfhan** [comment]
Ah super, yeah I discovered the actual color gradient function had stopped working since Dragonflight release or so. For some reason it only used the 0 or 1 colors, never the gradient inbetween. Once I got that working it revealed the color values were a bit wonky, because I had measured threat situation a little weird right at the 100% mark - relying on actual mob target in 10.0.7 solved most of it, but then colors also switch for those short random targeted spells which was not the intention :P
