### ISSUE TITLE
Can not change color 

### ISSUE THREAD

**Issue by Diuii** [int3ro/Nameplates_Threat#49]
Apperently i can not change the colors - whenver i want to change something i press on the color box and the color wheel pops up - once i selected the color i wanted i want to confirm it with the "Okay" button but nothing happens - the button seems to have lost its functionality..

**Comment by mikfhan** [comment]
Hmm yeah Blizzard keep deprecating the old UI button templates I use, try replacing your lua file with the below, if that helps:

https://raw.githubusercontent.com/int3ro/Nameplates_Threat/mikfhan/NamePlatesThreat.lua

It's a 4.5-release candidate, but I still struggle with Classic 1.15.4 looks like many more UI templates are getting removed soon.

**Comment by Diuii** [comment]
Replacing the File seems to work for me - thanks a lot!

**Comment by mikfhan** [comment]
Great! Most of deprecated UI for Classic I fixed now also, just waiting on more PTR blizz patches before 4.5-release is ready.
